# Generated by Django 2.2.3 on 2019-09-18 21:32

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizzeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la pizzeria')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección de la pizzeria')),
                ('phones', models.CharField(max_length=100, verbose_name='Teléfono(s) de la pizzeria')),
                ('email', models.EmailField(help_text='Puede ser el correo del notario', max_length=254, verbose_name='Correo electrónico principal de la pizzeria')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pizzeria_logos/', verbose_name='Logo de la pizzeria')),
                ('subdomain', models.CharField(max_length=50, unique=True, verbose_name='Subdominio')),
                ('has_physical_delivers', models.BooleanField(default=True, verbose_name='¿Acepta envíos físicos?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.Pizzeria')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
